### ISSUE TITLE
Bonjour!!!

### ISSUE THREAD

**Issue by carlospage** [SheepTester/primitive-cloud-server#1]
French
Je mais aucun dossier ou fichier pour l'instant. 
English 
I but no folder or file yet.

**Comment by SheepTester** [comment]
Hi! Unfortunately, I'm not sure what you're saying based on the English translation. Perhaps you could give more details?

If the problem is that you do not have the files for this repository on your computer, you can do

```sh
git clone https://github.com/SheepTester/primitive-cloud-server.git
cd primitive-cloud-server
npm install
npm start
```

in the command line.

---

In French, by Google Translate / En français, par Google Translate:

Salut! Malheureusement, je ne suis pas sûr de ce que vous dites basé sur la traduction anglaise. Peut-être pourriez-vous donner plus de détails?

Si le problème est que vous n'avez pas les fichiers de ce référentiel sur votre ordinateur, vous pouvez le faire

```sh
git clone https://github.com/SheepTester/primitive-cloud-server.git
cd primitive-cloud-server
npm install
npm start
```

dans la ligne de commande.

**Comment by SheepTester** [comment]
If you still have problems, you can open a new issue. / Si vous avez toujours des problèmes, vous pouvez ouvrir un nouveau problème.
